### ISSUE TITLE
Not working as expected on Firefox

### ISSUE THREAD

**Issue by AgtLucas** [gonzalonunez/gonzalonunez.me#12]
Hi @gonzalonunez! :)

I just want to report that your website isn't working as expected on Firefox. :/

<img width="1792" alt="screen shot 2018-02-18 at 19 32 01" src="https://user-images.githubusercontent.com/1909761/36355376-8c3133ec-14e2-11e8-8f97-ee7586247952.png">

**Comment by gonzalonunez** [comment]
Omg!! Thanks for reporting this, really appreciate it @AgtLucas 🙏🏻

**Comment by AgtLucas** [comment]
@gonzalonunez No worries! :)
